// API "goa-pubsubhubbub-subscriber": Application User Types
//
// Code generated by goagen v1.1.0-dirty, DO NOT EDIT.
//
// Command:
// $ goagen
// --design=github.com/blueoceans/goa-pubsubhubbub-subscriber/design
// --out=$(GOPATH)/src/github.com/blueoceans/goa-pubsubhubbub-subscriber
// --version=v1.2.0-dirty

package app
