// API "goa-pubsubhubbub-subscriber": hub TestHelpers
//
// Code generated by goagen v1.1.0-dirty, DO NOT EDIT.
//
// Command:
// $ goagen
// --design=github.com/blueoceans/goa-pubsubhubbub-subscriber/design
// --out=$(GOPATH)/src/github.com/blueoceans/goa-pubsubhubbub-subscriber
// --version=v1.2.0-dirty

package test

import (
	"bytes"
	"fmt"
	"github.com/blueoceans/goa-pubsubhubbub-subscriber/app"
	"github.com/goadesign/goa"
	"github.com/goadesign/goa/goatest"
	"golang.org/x/net/context"
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"net/url"
)

// NotifyHubOK runs the method Notify of the given controller with the given parameters.
// It returns the response writer so it's possible to inspect the response headers.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func NotifyHubOK(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.HubController) http.ResponseWriter {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Setup request context
	rw := httptest.NewRecorder()
	u := &url.URL{
		Path: fmt.Sprintf("/subscriber"),
	}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "HubTest"), rw, req, prms)
	notifyCtx, _err := app.NewNotifyHubContext(goaCtx, req, service)
	if _err != nil {
		panic("invalid test data " + _err.Error()) // bug
	}

	// Perform action
	_err = ctrl.Notify(notifyCtx)

	// Validate response
	if _err != nil {
		t.Fatalf("controller returned %+v, logs:\n%s", _err, logBuf.String())
	}
	if rw.Code != 200 {
		t.Errorf("invalid response status code: got %+v, expected 200", rw.Code)
	}

	// Return results
	return rw
}

// VerifiyHubOK runs the method Verifiy of the given controller with the given parameters.
// It returns the response writer so it's possible to inspect the response headers.
// If ctx is nil then context.Background() is used.
// If service is nil then a default service is created.
func VerifiyHubOK(t goatest.TInterface, ctx context.Context, service *goa.Service, ctrl app.HubController, hubChallenge *string, hubLeaseSeconds *float64, hubMode string, hubReason *string, hubTopic string) http.ResponseWriter {
	// Setup service
	var (
		logBuf bytes.Buffer
		resp   interface{}

		respSetter goatest.ResponseSetterFunc = func(r interface{}) { resp = r }
	)
	if service == nil {
		service = goatest.Service(&logBuf, respSetter)
	} else {
		logger := log.New(&logBuf, "", log.Ltime)
		service.WithLogger(goa.NewLogger(logger))
		newEncoder := func(io.Writer) goa.Encoder { return respSetter }
		service.Encoder = goa.NewHTTPEncoder() // Make sure the code ends up using this decoder
		service.Encoder.Register(newEncoder, "*/*")
	}

	// Setup request context
	rw := httptest.NewRecorder()
	query := url.Values{}
	if hubChallenge != nil {
		sliceVal := []string{*hubChallenge}
		query["hub.challenge"] = sliceVal
	}
	if hubLeaseSeconds != nil {
		sliceVal := []string{fmt.Sprintf("%v", *hubLeaseSeconds)}
		query["hub.lease_seconds"] = sliceVal
	}
	{
		sliceVal := []string{hubMode}
		query["hub.mode"] = sliceVal
	}
	if hubReason != nil {
		sliceVal := []string{*hubReason}
		query["hub.reason"] = sliceVal
	}
	{
		sliceVal := []string{hubTopic}
		query["hub.topic"] = sliceVal
	}
	u := &url.URL{
		Path:     fmt.Sprintf("/subscriber"),
		RawQuery: query.Encode(),
	}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		panic("invalid test " + err.Error()) // bug
	}
	prms := url.Values{}
	if hubChallenge != nil {
		sliceVal := []string{*hubChallenge}
		prms["hub.challenge"] = sliceVal
	}
	if hubLeaseSeconds != nil {
		sliceVal := []string{fmt.Sprintf("%v", *hubLeaseSeconds)}
		prms["hub.lease_seconds"] = sliceVal
	}
	{
		sliceVal := []string{hubMode}
		prms["hub.mode"] = sliceVal
	}
	if hubReason != nil {
		sliceVal := []string{*hubReason}
		prms["hub.reason"] = sliceVal
	}
	{
		sliceVal := []string{hubTopic}
		prms["hub.topic"] = sliceVal
	}
	if ctx == nil {
		ctx = context.Background()
	}
	goaCtx := goa.NewContext(goa.WithAction(ctx, "HubTest"), rw, req, prms)
	verifiyCtx, _err := app.NewVerifiyHubContext(goaCtx, req, service)
	if _err != nil {
		panic("invalid test data " + _err.Error()) // bug
	}

	// Perform action
	_err = ctrl.Verifiy(verifiyCtx)

	// Validate response
	if _err != nil {
		t.Fatalf("controller returned %+v, logs:\n%s", _err, logBuf.String())
	}
	if rw.Code != 200 {
		t.Errorf("invalid response status code: got %+v, expected 200", rw.Code)
	}

	// Return results
	return rw
}
